title: "FAQ | Department of Computer Engineering"
description: "FAQ | Department of Computer Engineering"
baseurl: "/faq" # the subpath of your site, e.g. /blog

theme: jekyll-theme-minimal

plugins:
    - jekyll-seo-tag
    - jekyll-readme-index
    - jekyll-sitemap
